Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.provider "vmware_desktop" do |v|
 #   v.name = "vag-u22"
    v.memory = 9000
    v.cpus = 4
  end
  config.vm.provision "shell", path: "scripts/common.sh"
  config.vm.provision "shell", path: "scripts/notes.sh"
#   # config.vm.provision "shell", path: "scripts/docker.sh" 
  
#   # config.vm.provision "shell", path: "scripts/docker-verify2.sh", privileged: false
#   # # config.vm.provision "shell", path: "scripts/kubectl.sh", privileged: false
#   # config.vm.provision "shell", path: "scripts/minikube.sh", privileged: false
#   # config.vm.provision "shell", path: "scripts/check-node.sh", privileged: false
#   # config.vm.provision "shell", path: "scripts/"
end