Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.provider "vmware_desktop" do |v|
 #   v.name = "vag-u22"
    v.memory = 4000
    v.cpus = 4
  end
  config.vm.provision "shell", path: "scripts/common.sh"
  config.vm.provision "shell", path: "scripts/jenkins.sh"
end