Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update -y
        # sudo apt upgrade -y
        echo "10.0.0.11  master" >> /etc/hosts
        echo "10.0.0.21  node_1" >> /etc/hosts
        echo "10.0.0.22  node_2" >> /etc/hosts
    SHELL
    
    config.vm.define "master" do |master|
      master.vm.box = "bento/ubuntu-20.04"
      master.vm.hostname = "master"
      master.vm.network "private_network", ip: "10.0.0.11"
      master.vm.provider "virtualbox" do |vb|
          vb.memory = 4048
          vb.cpus = 2
      end
      master.vm.provision "shell", path: "scripts/common.sh"
      master.vm.provision "shell", path: "scripts/master.sh"
    end

    (1..2).each do |i|
  
    config.vm.define "node0#{i}" do |node|
      node.vm.box = "bento/ubuntu-20.04"
      node.vm.hostname = "node0#{i}"
      node.vm.network "private_network", ip: "10.0.0.2#{i}"
      node.vm.provider "virtualbox" do |vb|
          vb.memory = 3000
          vb.cpus = 2
      end
      node.vm.provision "shell", path: "scripts/common.sh"
      node.vm.provision "shell", path: "scripts/node.sh"
    end
    
    end
  end



  