Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: <<-SHELL
        apt-get update -y
#        echo "10.0.0.10  lb" >> /etc/hosts

        echo "10.0.0.11  master-01" >> /etc/hosts
#        echo "10.0.0.12  master-02" >> /etc/hosts
#        echo "10.0.0.13  master-03" >> /etc/hosts

        echo "10.0.0.21  worker-01" >> /etc/hosts
        echo "10.0.0.22  worker-02" >> /etc/hosts
#        echo "10.0.0.23  worker-03" >> /etc/hosts
#        echo "10.0.0.24  worker-04" >> /etc/hosts

    SHELL

# ##below is to create more than one master
#   (1..3).each do |i|    
#   config.vm.define "master0#{i}" do |master|
#     #master.vm.box_download_insecure = true    
#     master.vm.box = "bento/ubuntu-20.04"       
#     master.vm.network "private_network", ip: "10.0.0.1#{i}"
#     master.vm.hostname = "master-0#{i}"
#     master.vm.provider "virtualbox" do |v|
#       v.name = "master-0#{i}"
#       v.memory = 2048
#       v.cpus = 2
#     end
#     #   master.vm.provision "shell", path: "scripts/common.sh"
#     #   master.vm.provision "shell", path: "scripts/node.sh"    
#   end
# end

## below is to create one master
    config.vm.define "master-01" do |master|
      master.vm.box = "bento/ubuntu-20.04"
      master.vm.hostname = "master-01"
      master.vm.network "private_network", ip: "10.0.0.11"
      master.vm.provider "virtualbox" do |v|
          v.name = "master-01"
          v.memory = 2048
          v.cpus = 2
      end
      master.vm.provision "shell", path: "scripts/common.sh"
     # master.vm.provision "shell", path: "scripts/master.sh"
    end



# ## below is to create more than one worker node
#     (1..3).each do |i|
  
#     config.vm.define "node0#{i}" do |node|
#       node.vm.box = "bento/ubuntu-20.04"
#       node.vm.hostname = "worker-0#{i}"
#       node.vm.network "private_network", ip: "10.0.0.2#{i}"
#       node.vm.provider "virtualbox" do |v|
#           v.name = "worker0#{i}"
#           v.memory = 3000
#           v.cpus = 1
#       end
#     #   node.vm.provision "shell", path: "scripts/common.sh"
#     #   node.vm.provision "shell", path: "scripts/node.sh"
#     end
    
#     end

## below is to create one worker node

  config.vm.define "worker-01" do |worker|
  #   worker.vm.box_download_insecure = true 
    worker.vm.box = "bento/ubuntu-20.04"        ## For ubuntu 18.04 use - hashicorp/bionic64
    worker.vm.network "private_network", ip: "10.0.0.21"
    worker.vm.hostname = "worker-01"
    worker.vm.provider "virtualbox" do |v|
      v.name = "worker-01"
      v.memory = 1024
      v.cpus = 1
    end
    #   node.vm.provision "shell", path: "scripts/common.sh"
    #   node.vm.provision "shell", path: "scripts/node.sh"
  end

end